version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8001"
    command: python /news_website/news_app/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/news_website
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB : postgres
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
volumes:
  postgres_data:

    